version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: CI=true yarn run build

workflows:
  install-and-run:
    jobs:
      - build
